### ISSUE TITLE
面对这个程序我有些楞

### ISSUE THREAD

**Issue by xuelainiao** [kdwnil/baidunetdisk#2]
尊敬的作者同志，
我本来看到标题进来的，然后通过测试网址，将自己网盘的一个文件做分享复制出来链接给测试站，但并没有获取得到直链，或许是我哪里操作有误，求教具体操作演示~~~

**Comment by yaoyichi2011** [comment]
可能由以下原因造成的：
1.现在百度云客户端的分享链接会进行跳转造成数据抓取的失败
2.分享链接带密码
3.未知原因（日常连不上）
第一种问题我在修；第二种代码里面注释着，因为验证码还是比较麻烦所以没做；第三种问题就。。。只能看脸了

**Comment by yaoyichi2011** [comment]
百度更换了logid导致获取失败，演示站已经修复了，仓库也会在新版本更新此参数，感谢您的反馈

**Comment by yaoyichi2011** [comment]
fix #24
